### ISSUE TITLE
Happy new year

### ISSUE THREAD

**Issue by ghost** [hasufell/prism-overlay#1]
Hello Julian,

How ya doin ?

I would like to thank you for the C book (ansi c) by dennis ritchie which has served me pretty well to understand C better and solve couple issues.

What do you think about my second gui program written in c - https://github.com/wifiextender/pdf2img-c ?

Best regards,
Aaron Caffrey

**Comment by hasufell** [comment]
happy new year, but the bug is still invalid :P

**Comment by ghost** [comment]
Hehe, thanks for reporting issues. Added internatilization via gettex and was wondering can you tranlate en_GB.po in Deutsch ?
