### ISSUE TITLE
net-fs/tahoe-lafs on sabayon. 

### ISSUE THREAD

**Issue by necrose99** [hasufell/prism-overlay#2]
[32;01m \* [39;49;00mPackage:    net-fs/tahoe-lafs-1.10.0-r2
[32;01m \* [39;49;00mRepository: gentoo
[32;01m \* [39;49;00mMaintainer: maintainer-needed@gentoo.org
[32;01m \* [39;49;00mUpstream:  
            https://tahoe-lafs.org/trac/tahoe-lafs/wiki/ViewTickets

[32;01m \* [39;49;00mUSE:        abi_x86_64 amd64 elibc_glibc kernel_linux python_targets_python2_7 userland_GNU
[32;01m \* [39;49;00mFEATURES:   compressdebug preserve-libs sandbox splitdebug userpriv usersandbox

> > > Unpacking source...
> > > Unpacking allmydata-tahoe-1.10.0.tar.bz2 to /var/tmp/portage/net-fs/tahoe-lafs-1.10.0-r2/work
> > > Source unpacked in /var/tmp/portage/net-fs/tahoe-lafs-1.10.0-r2/work
> > > Preparing source in /var/tmp/portage/net-fs/tahoe-lafs-1.10.0-r2/work/allmydata-tahoe-1.10.0 ...
> > >  [32;01m_[0m Applying tahoe-lafs-1.10.0-setup.patch ...
> > > [A[72C [34;01m[ [32;01mok[34;01m ][0m
> > >  [32;01m_[0m Applying tahoe-lafs-1.10.0-ifconfig.patch ...
> > > [A[72C [34;01m[ [32;01mok[34;01m ][0m
> > > Source prepared.
> > > Configuring source in /var/tmp/portage/net-fs/tahoe-lafs-1.10.0-r2/work/allmydata-tahoe-1.10.0 ...
> > > Source configured.
> > > Compiling source in /var/tmp/portage/net-fs/tahoe-lafs-1.10.0-r2/work/allmydata-tahoe-1.10.0 ...
> > >  [32;01m_[0m python2_7: running distutils-r1_run_phase distutils-r1_python_compile
> > > /usr/bin/python2.7 setup.py build
> > > Traceback (most recent call last):
> > >   File "setup.py", line 73, in <module>
> > >     import setuptools
> > >   File "/usr/lib64/python2.7/site-packages/setuptools/**init**.py", line 11, in <module>
> > >     from setuptools.extension import Extension
> > >   File "/usr/lib64/python2.7/site-packages/setuptools/extension.py", line 8, in <module>
> > >     from .dist import _get_unpatched
> > >   File "/usr/lib64/python2.7/site-packages/setuptools/dist.py", line 19, in <module>
> > >     import pkg_resources
> > >   File "/usr/lib64/python2.7/site-packages/pkg_resources/__init__.py", line 3018, in <module>
> > >     working_set = WorkingSet._build_master()
> > >   File "/usr/lib64/python2.7/site-packages/pkg_resources/__init__.py", line 614, in _build_master
> > >     return cls._build_from_requirements(__requires__)
> > >   File "/usr/lib64/python2.7/site-packages/pkg_resources/**init**.py", line 627, in _build_from_requirements
> > >     dists = ws.resolve(reqs, Environment())
> > >   File "/usr/lib64/python2.7/site-packages/pkg_resources/__init__.py", line 805, in resolve
> > >     raise DistributionNotFound(req)
> > > pkg_resources.DistributionNotFound: pycrypto==2.1.0,==2.3,>=2.4.1
> > >  [31;01m_[0m ERROR: net-fs/tahoe-lafs-1.10.0-r2::gentoo failed (compile phase):
> > >  [31;01m_[0m   (no error message)
> > >  [31;01m_[0m 
> > >  [31;01m_[0m Call stack:
> > >  [31;01m_[0m     ebuild.sh, line   93:  Called src_compile
> > >  [31;01m_[0m   environment, line 3730:  Called distutils-r1_src_compile
> > >  [31;01m_[0m   environment, line 1128:  Called _distutils-r1_run_foreach_impl 'distutils-r1_python_compile'
> > >  [31;01m_[0m   environment, line  369:  Called python_foreach_impl 'distutils-r1_run_phase' 'distutils-r1_python_compile'
> > >  [31;01m_[0m   environment, line 3319:  Called multibuild_foreach_variant '_python_multibuild_wrapper' 'distutils-r1_run_phase' 'distutils-r1_python_compile'
> > >  [31;01m_[0m   environment, line 2438:  Called _multibuild_run '_python_multibuild_wrapper' 'distutils-r1_run_phase' 'distutils-r1_python_compile'
> > >  [31;01m_[0m   environment, line 2436:  Called _python_multibuild_wrapper 'distutils-r1_run_phase' 'distutils-r1_python_compile'
> > >  [31;01m_[0m   environment, line  815:  Called distutils-r1_run_phase 'distutils-r1_python_compile'
> > >  [31;01m_[0m   environment, line 1119:  Called distutils-r1_python_compile
> > >  [31;01m_[0m   environment, line 1004:  Called esetup.py 'build'
> > >  [31;01m_[0m   environment, line 1607:  Called die
> > >  [31;01m_[0m The specific snippet of code:
> > >  [31;01m_[0m       "${@}" || die
> > >  [31;01m_[0m 
> > >  [31;01m_[0m If you need support, post the output of `emerge --info '=net-fs/tahoe-lafs-1.10.0-r2::gentoo'`,
> > >  [31;01m_[0m the complete build log and the output of `emerge -pqv '=net-fs/tahoe-lafs-1.10.0-r2::gentoo'`.
> > >  [31;01m_[0m The complete build log is located at '/var/tmp/portage/net-fs/tahoe-lafs-1.10.0-r2/temp/build.log'.
> > >  [31;01m_[0m The ebuild environment file is located at '/var/tmp/portage/net-fs/tahoe-lafs-1.10.0-r2/temp/environment'.
> > >  [31;01m_[0m Working directory: '/var/tmp/portage/net-fs/tahoe-lafs-1.10.0-r2/work/allmydata-tahoe-1.10.0'
> > >  [31;01m*[0m S: '/var/tmp/portage/net-fs/tahoe-lafs-1.10.0-r2/work/allmydata-tahoe-1.10.0'

**Comment by necrose99** [comment]
other tools including zulucrypt onioncat ,dianara builds with ease.  or the occasion --nodeps
as package is already on sabayon bin repo (and installed) . spike-pentesting.org for ours or you can always hit us up in #spike-pentesting #spike-pentesting-dev on freenode or via GITTER app. were always happy to have more Security apps to test.

**Comment by hasufell** [comment]
it seems it cannot find pycrypto... is that installed as binpkg?

**Comment by necrose99** [comment]
yes it is normally if not I can try to force an upgrade . dev-python/pycryptopp

missing dev-python/pycrypto so I'll add it from portage or entropy I'm surprised it wasn't pulled in.
via emerge but no biggy. 
I still need to parse missing from my old world file HDD fail.... been slow at re-adding the back  
dev-python/pycrypto-2.6.1-r1 as bin will try again. 

I've got a few gimpy quality ebuilds to add to our community overlay to try and test bump eapi from 3, 4 to 5 (my ebuild foo is new and feeble) if i'm lucky i might get them building again , if not i'll put them as close as i can and contrib them back .... github.com/Spike-Pentesting 
github.com/Sabayon-Labs/spike-community-overlay (_ebuild tips hint welcomed_) 
so far it's Anaconda installer has caused us more unforeseen delays. .
 ... I'm just a hands on IT security Admin, and  IT security grad student 

hopefully I can get Alien vault's open Siem to run, as ebuild or get damn close enough , 
we have no qualms testing more stuff you have , may forensic ebuilds need some revival. 
.  pastie for emerge logs , so ask mulder or skullbocks, they've more q/a than I, hopefully i can get them added to the repo builder , spike repo sometimes the ci-server will auto-bump & test  an ebuild via euscan , thus might save you some work. 
Dev channel: #spike-pentesting-dev 
<SpikeBuilder64> Witchcraft@spike64builder: <c1650471c5509877b9347f88af31ec08c8a12a53> Compiled: app-benchmarks/phoronix-test-suite::spike app-office/mdp::spike dev-libs/gecode::spike dev-util/capstone::spike net-analyzer/bro::spike net-misc/fwknop::spike net-misc/patator::spike net-proxy/zaproxy::spike net-wireless/
<SpikeBuilder64> virtualradar-bin::spike www-client/palemoon::spike x11-misc/xwrited::spike
